// 从 ShapeRegistry 生成 TypeScript .d.ts。
//
// 输入:已打开的 Pearl 实例(其 shape registry 是事件流的派生)
// 输出:可被项目 import 的类型源码

import { writeFileSync } from "node:fs";

import type { Primitive } from "../types.js";
import type { ShapeRegistry } from "../schema/registry.js";

export type GenTypesOptions = {
  /** 头部注释,默认有一条 auto-generated 提示。 */
  header?: string;
  /** Attrs 接口名后缀(默认 "Attrs")。 */
  attrsSuffix?: string;
  /** Entity 接口名后缀(默认 "Entity")。 */
  entitySuffix?: string;
};

export function generateTypes(
  registry: ShapeRegistry,
  opts: GenTypesOptions = {},
): string {
  const header =
    opts.header ??
    "// Auto-generated by pearl gen-types. Do not edit by hand — regenerate from the event log.";
  const attrsSuffix = opts.attrsSuffix ?? "Attrs";
  const entitySuffix = opts.entitySuffix ?? "Entity";

  const types = registry.entityTypes().slice().sort();
  const lines: string[] = [];
  lines.push(header, "");

  const entityIdents: Record<string, string> = {};

  for (const t of types) {
    const ident = pascal(t);
    entityIdents[t] = `${ident}${entitySuffix}`;
    const shape = registry.shapeOf(t);

    lines.push(`export interface ${ident}${attrsSuffix} {`);
    const keys = [...shape.keys()].sort();
    if (keys.length === 0) {
      lines.push(`  // (no attributes observed yet)`);
    }
    for (const attr of keys) {
      const prim = shape.get(attr)!;
      lines.push(`  ${safeKey(attr)}?: ${tsType(prim)};`);
    }
    lines.push(`}`, "");

    lines.push(`export interface ${ident}${entitySuffix} {`);
    lines.push(`  id: string;`);
    lines.push(`  type: ${JSON.stringify(t)};`);
    lines.push(`  attrs: ${ident}${attrsSuffix};`);
    lines.push(`  version: number;`);
    lines.push(`  createdAt: number;`);
    lines.push(`  updatedAt: number;`);
    lines.push(`  deleted?: boolean;`);
    lines.push(`}`, "");
  }

  // 索引映射
  lines.push(`export type EntityByType = {`);
  if (types.length === 0) {
    lines.push(`  // (no entity types observed yet)`);
  }
  for (const t of types) {
    lines.push(`  ${JSON.stringify(t)}: ${entityIdents[t]};`);
  }
  lines.push(`};`, "");

  lines.push(`export type EntityType = keyof EntityByType;`);

  return lines.join("\n") + "\n";
}

export function writeTypes(
  registry: ShapeRegistry,
  outputPath: string,
  opts: GenTypesOptions = {},
): void {
  writeFileSync(outputPath, generateTypes(registry, opts), "utf8");
}

function tsType(p: Primitive): string {
  switch (p) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
      return "Record<string, unknown>";
  }
}

function pascal(s: string): string {
  if (s.length === 0) return "Anonymous";
  const parts = s.split(/[\s_\-./]+/).filter(Boolean);
  if (parts.length === 0) return "Anonymous";
  let ident = parts
    .map((p) => p[0]!.toUpperCase() + p.slice(1).toLowerCase())
    .join("");
  if (!/^[A-Z]/.test(ident)) ident = "_" + ident;
  return ident.replace(/[^a-zA-Z0-9_]/g, "_");
}

function safeKey(k: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
}
